"""
Common constants module
"""

from .main import (
    SEA_LEVEL_TEMPERATURE,
    SEA_LEVEL_PRESSURE,
    TEMPERATURE_LAPSE_RATE,
    MOLAR_GAS_CONSTANT,
    MOLAR_MASS_FOR_DRY_AIR,
    GRAVITATIONAL_ACCELERATION,
    SEA_LEVEL_AIR_DYNAMIC_VISCOSITY,
    SUTHERLAND_CONSTANT,
)
